language: node_js
node_js:
  - "10"
  - "12"
  - "8"
  - lts/*
before_script:
  - npm install
  - npm install nyc@13 lerna --global
  - lerna bootstrap --ci
script:
  - "lerna add @iarna/toml@^2.2.1"
  - "lerna add hjson@^3.1.2"
  - "lerna add ini@^1.3.5"
  - "lerna add js-yaml@^3.12.0"
  - "lerna add json5@^2.1.0"
  - "lerna run build"

after_success:
  - npm install coveralls@~3.0.0 --global
  - nyc report --reporter=text-lcov | coveralls
before_deploy:
  - lerna run clean
  - lerna run build:prod
os:
  - linux
  - osx
stages:
  - lint
  - test
  # - deploy
jobs:
  include:
    - node_js: lts/*
      os: linux
      script:
        - lerna run lint
      stage: lint
    - stage: test
      script:
        - "nyc lerna run test"
    # - deploy:
    #     skip_cleanup: true
    #     provider: npm
    #     email: arylo.open+npm@gmail.com
    #     api_key: "${NPM_TOKEN}"
    #     "on":
    #       branch: master
    #   node_js: lts/*
    #   os: linux
    #   script: skip
    #   stage: deploy
